server:
  port: 8001

spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml

  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 3
  mvc:
    view:
      prefix: /templates/
      suffix: .html

short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: 824c511f0997586ea016f979fdb23087